server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/**
          filters:
            - RewritePath=/baeldung/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"

management.endpoint.gateway.enabled: "true"


#spring.cloud.gateway.routes=[{id=baeldung_route, uri=http://baeldung.com/spring-cloud-gateway, predicates=[Path=/baeldung]}]
