server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com/spring-cloud-gateway
          predicates:
            - Path=/baeldung

management:
  endpoints:
    web:
      exposure:
        include: "*"

management.endpoint.gateway.enabled: "true"


#spring.cloud.gateway.routes=[{id=baeldung_route, uri=http://baeldung.com/spring-cloud-gateway, predicates=[Path=/baeldung]}]
