server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

management:
  endpoints:
    web:
      exposure:
        include: "*"

management.endpoint.gateway.enabled: "true"


spring:
  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/**
          filters:
            - RewritePath=/baeldung/(?<path>.*), /$\{path}
        - id: callee_route
          uri: http://localhost:50900
          predicates:
            - Path=/callee/**
          filters:
            - RewritePath=/callee/(?<path>.*), /$\{path}
#            - AddRequestHeader=X-TenantId, 555

  security:
    oauth2:
      base-uri: "http://127.0.0.1:30200/oidc"
      authorization-uri: "http://127.0.0.1:30200/oidc/auth"
      user-name-attribute: "sub"
      #base-uri: http://localhost:30200/oidc/realms/tenant-{tenantId}/protocol/openid-connect
      #authorization-uri: http://localhost:30200/oidc/realms/tenant-{tenantId}/protocol/openid-connect/auth
      #logout-uri: http://localhost:30200/oidc/realms/tenant-{tenantId}/protocol/openid-connect/logout
      #user-name-attribute: "preferred_username"

      client-id: "oauth2-proxy"
      client-secret: "none"

security.authentication.enabled: "true"

logging.level.root: "WARN"
logging.level.org.springframework: "DEBUG"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"