server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

management:
  endpoints:
    web:
      exposure:
        include: "*"

management.endpoint.gateway.enabled: "true"


spring:
  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      routes:
        - id: callee_route
          uri: http://callee-service-application:50900
          predicates:
            - Path=/callee/**
          filters:
            - RewritePath=/callee/(?<path>.*), /$\{path}

security.authentication.enabled: "true"

logging.level.root: "WARN"
logging.level.org.springframework: "DEBUG"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"