spring:
  cloud:
    gateway:
      routes:
        - id: callee_route
          uri: http://callee-service-application:50900
          predicates:
            - Path=/callee/**
          filters:
            - RewritePath=/callee/(?<path>.*), /$\{path}

#spring.webflux.base-path: "/gateway"